_format_version: "3.0"
_transform: false

services:
- name: meu-servico
  url: https://mockbin.org
  routes:
  - name: localhost
    paths:
    - "/meu-servico"

plugins:
- name: rate-limiting
  config:
    second: 5
    